services:
  db:
    image: postgres:16
    container_name: questboard-db
    environment:
      POSTGRES_DB: questboard
      POSTGRES_USER: questboard
      POSTGRES_PASSWORD: questboard
    ports:
      - "5432:5432"
    volumes:
      - questboard_pgdata:/var/lib/postgresql/data

  backend:
      build:
        context: ./backend
      container_name: questboard-backend
      ports:
        - "8080:8080"
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/questboard
        SPRING_DATASOURCE_USERNAME: questboard
        SPRING_DATASOURCE_PASSWORD: questboard
      depends_on:
        - db

volumes:
  questboard_pgdata:


